import { El_Messiri } from 'next/font/google';
import "./globals.css";
import Footer from '@/components/footer/footer';
import Navbar from '@/components/navbar/navbar';

const messiri = El_Messiri({
  subsets: ['latin'],
})

export const metadata = {
  title: "On Dm Tech",
  description: "Generated by On Dm Tech",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${messiri.className} antialiased`}>
        <Navbar />
        <div className='mt-24'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
